"""Profile the merged data and write DATA_DICTIONARY.md.

Column meanings come from the data provider's (Vesta) public description on the
competition forum. Most columns are deliberately masked, so "meaning" is often
only the family description.
"""
from __future__ import annotations

import re

import numpy as np
import pandas as pd

from src.config import ROOT

FAMILY_MEANING = [
    (r"^TransactionID$", "Transaction identifier. Join key to the identity table."),
    (r"^TransactionDT$", "Seconds offset from an undisclosed reference time. Used only as an ordering index and for relative durations; not a timestamp."),
    (r"^TransactionAmt$", "Transaction amount in USD."),
    (r"^isFraud$", "Label. 1 = the card had a reported chargeback; later transactions on the same account/email/address inside the provider's window are also labelled 1. Reflects chargebacks, not confirmed fraud."),
    (r"^ProductCD$", "Product code (masked; five values). Used here as a merchant/product proxy."),
    (r"^card[1-6]$", "Payment card attributes (masked): card type, category, issuing bank, country. card4 = network, card6 = debit/credit."),
    (r"^addr1$", "Billing region (masked)."),
    (r"^addr2$", "Billing country (masked)."),
    (r"^dist[12]$", "Distances between masked address-like entities (billing, mailing, IP, phone area)."),
    (r"^P_emaildomain$", "Purchaser email domain."),
    (r"^R_emaildomain$", "Recipient email domain."),
    (r"^C\d+$", "Counts (masked), e.g. how many addresses are associated with the card."),
    (r"^D\d+$", "Time deltas in days (masked), e.g. days since previous transaction. D1 is widely read as days since the card/account relationship began."),
    (r"^M\d+$", "Match flags (masked), e.g. name on card matches address."),
    (r"^V\d+$", "Vesta-engineered features (masked): rankings, counts, entity relations."),
    (r"^id_\d+$", "Identity information (masked): network (IP, ISP, proxy) and digital signature (browser, OS, screen)."),
    (r"^DeviceType$", "Device type (desktop / mobile)."),
    (r"^DeviceInfo$", "Device description string."),
]

ID_COLUMNS = ["card1", "card2", "card3", "card4", "card5", "card6", "addr1", "addr2",
              "P_emaildomain", "R_emaildomain", "ProductCD", "DeviceInfo", "DeviceType",
              "id_30", "id_31", "id_33", "card_key", "uid"]


def meaning(col: str) -> str:
    for pat, text in FAMILY_MEANING:
        if re.match(pat, col):
            return text
    return "Unknown."


def profile(df: pd.DataFrame) -> dict:
    """Return a JSON-serialisable profile. ``df`` must carry ``split``, ``card_key``, ``uid``."""
    n = len(df)
    miss = df.isna().mean()
    day = (df["TransactionDT"] // 86400).astype(int)
    period = (day - day.min()) // 30
    by_period = (df.assign(period=period).groupby("period")
                 .agg(n=("isFraud", "size"), fraud_rate=("isFraud", "mean"),
                      dt_min=("TransactionDT", "min"), dt_max=("TransactionDT", "max")))
    fraud_amt = df["TransactionAmt"] * df["isFraud"]
    by_split = (df.assign(fraud_amt=fraud_amt).groupby("split").agg(n=("isFraud", "size"), n_fraud=("isFraud", "sum"),
                                         fraud_rate=("isFraud", "mean"),
                                         dt_min=("TransactionDT", "min"),
                                         dt_max=("TransactionDT", "max"),
                                         amt_fraud=("fraud_amt", "sum"),
                                         amt_total=("TransactionAmt", "sum"))
                .reindex(["train", "valid", "test"]))
    by_split["days"] = (by_split["dt_max"] - by_split["dt_min"]) / 86400.0
    return {
        "n_rows": int(n),
        "n_columns": int(df.shape[1]),
        "n_fraud": int(df["isFraud"].sum()),
        "fraud_rate": float(df["isFraud"].mean()),
        "dt_span_days": float((df["TransactionDT"].max() - df["TransactionDT"].min()) / 86400.0),
        "identity_match_rate": float(df["id_01"].notna().mean()) if "id_01" in df else None,
        "missingness": {c: float(v) for c, v in miss.items()},
        "cardinality": {c: int(df[c].nunique(dropna=True)) for c in ID_COLUMNS if c in df},
        "by_split": {s: {k: float(v) for k, v in row.items()} for s, row in by_split.iterrows()},
        "by_period": [{"period": int(i), **{k: float(v) for k, v in row.items()}}
                      for i, row in by_period.iterrows()],
    }


def write_data_dictionary(prof: dict, raw_columns: list[str]) -> None:
    L = []
    a = L.append
    a("# Data dictionary\n")
    a("Generated by `src/data/profile.py` from the merged labelled data "
      "(`train_transaction.csv` left-joined to `train_identity.csv` on `TransactionID`). "
      "Regenerated on every pipeline run; do not edit by hand.\n")
    a(f"- Rows: {prof['n_rows']:,}; raw columns after join: {len(raw_columns)}")
    a(f"- Fraud-labelled rows: {prof['n_fraud']:,} ({prof['fraud_rate']:.2%})")
    a(f"- Span of `TransactionDT`: {prof['dt_span_days']:.1f} days of relative time")
    a(f"- Share of transactions with an identity record: {prof['identity_match_rate']:.1%}\n")
    a("## Important caveats\n")
    a("- `TransactionDT` is a seconds offset from an unknown reference. It is treated as an "
      "ordering index only. Hour-of-day features derived from it assume the reference is "
      "midnight, which is unverified.")
    a("- `isFraud` reflects reported chargebacks, with propagation to later transactions on the "
      "same account. It is not confirmed fraud, and label maturity near the end of the data "
      "is unknown.")
    a("- Most columns are masked by the provider. Meanings below are family-level.\n")
    a("## Class balance per split\n")
    a("| Split | Rows | Fraud rows | Fraud rate | Fraud $ share | Relative days |")
    a("|---|---:|---:|---:|---:|---:|")
    for s, r in prof["by_split"].items():
        a(f"| {s} | {int(r['n']):,} | {int(r['n_fraud']):,} | {r['fraud_rate']:.2%} | "
          f"{r['amt_fraud'] / r['amt_total']:.2%} | {r['days']:.1f} |")
    a("\n## Class balance per 30-day period of relative time\n")
    a("| Period | Rows | Fraud rate |")
    a("|---:|---:|---:|")
    for r in prof["by_period"]:
        a(f"| {r['period']} | {int(r['n']):,} | {r['fraud_rate']:.2%} |")
    a("\n## Identifier cardinality (distinct non-missing values)\n")
    a("| Column | Distinct | Missing |")
    a("|---|---:|---:|")
    for c, k in prof["cardinality"].items():
        m = prof["missingness"].get(c, 0.0)
        a(f"| `{c}` | {k:,} | {m:.1%} |")
    a("\n`card_key` and `uid` are derived keys; see DECISIONS.md D0.4.\n")
    a("## Columns\n")
    a("V columns are summarised as a family to keep this readable; per-column missingness "
      "for them is in `outputs/tables/missingness.csv`.\n")
    a("| Column | Missing | Meaning |")
    a("|---|---:|---|")
    v_cols = [c for c in raw_columns if re.match(r"^V\d+$", c)]
    for c in raw_columns:
        if c in v_cols:
            continue
        a(f"| `{c}` | {prof['missingness'][c]:.1%} | {meaning(c)} |")
    if v_cols:
        vm = np.array([prof["missingness"][c] for c in v_cols])
        a(f"| `V1`–`V{len(v_cols)}` ({len(v_cols)} cols) | {vm.min():.1%}–{vm.max():.1%} "
          f"(median {np.median(vm):.1%}) | {meaning('V1')} |")
    (ROOT / "DATA_DICTIONARY.md").write_text("\n".join(L) + "\n", encoding="utf-8")
